#!/usr/bin/env python3
"""Generate docs/assets/elements-data.js from docs/assets/elements.json.

Source: Bowserinator/Periodic-Table-JSON (PeriodicTableJSON.json).
Keeps only the fields needed by the room visualisation and normalises:
  - ypos for the extended periodic table (lanthanides -> row 8, actinides -> row 9)
  - category names ("unknown, probably X" -> X)
  - missing CPK hex colours -> a synthetic fallback palette

Usage:  python scripts/build_elements_data.py
Output: docs/assets/elements-data.js   (window.ELEMENTS, window.ELEMENT_CATEGORIES)
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "docs/assets/elements.json"
OUT = ROOT / "docs/assets/elements-data.js"

# Normalise verbose bowserinator category strings to stable keys
CATEGORY_ALIASES = {
    "unknown, probably transition metal": "transition metal",
    "unknown, probably post-transition metal": "post-transition metal",
    "unknown, probably metalloid": "metalloid",
    "unknown, predicted to be noble gas": "noble gas",
}

CATEGORY_ORDER = [
    ("alkali metal", "Alkali metal"),
    ("alkaline earth metal", "Alkaline earth"),
    ("transition metal", "Transition metal"),
    ("post-transition metal", "Post-transition"),
    ("lanthanide", "Lanthanide"),
    ("actinide", "Actinide"),
    ("diatomic nonmetal", "Nonmetal (diatomic)"),
    ("polyatomic nonmetal", "Nonmetal (polyatomic)"),
    ("metalloid", "Metalloid"),
    ("halogen", "Halogen"),
    ("noble gas", "Noble gas"),
]

# Fallback CPK-ish colours for the synthetic elements without a standard colour
FALLBACK_CPK = [
    "b0b0b0", "a8a8c0", "9090d0", "80b0a0", "c0a080", "d0d060", "d080a0",
    "80c0ff", "a0e0e0", "f0c0a0",
]

def main() -> None:
    data = json.loads(SRC.read_text(encoding="utf-8"))
    els = [e for e in data["elements"] if e["number"] in range(1, 119)]
    els.sort(key=lambda e: e["number"])

    normalised = {}
    for e in els:
        cat = CATEGORY_ALIASES.get(e["category"], e["category"])
        normalised.setdefault(cat, []).append(e)

    cpk_missing = sorted({e["number"] for cat in normalised.values() for e in cat if not e.get("cpk-hex")})
    fallback = {num: FALLBACK_CPK[i % len(FALLBACK_CPK)] for i, num in enumerate(cpk_missing)}
    for e in els:
        if not e.get("cpk-hex"):
            e["cpk-hex"] = fallback.get(e["number"], FALLBACK_CPK[e["number"] % len(FALLBACK_CPK)])

    def row_of(e):
        y = e["ypos"]
        if y >= 9:
            return y - 1          # lanthanides 9->8, actinides 10->9
        return y

    summary_of = lambda e: (e.get("summary") or "").strip()[:260]

    compact = [
        {
            "n": e["number"],
            "s": e["symbol"],
            "name": e["name"],
            "x": e["xpos"],
            "row": row_of(e),
            "cat": CATEGORY_ALIASES.get(e["category"], e["category"]),
            "c": e["cpk-hex"].lstrip("#"),
            "m": e.get("atomic_mass"),
            "sh": e.get("shells") or [],
            "phase": e.get("phase"),
            "melt": e.get("melt"),
            "boil": e.get("boil"),
            "dens": e.get("density"),
            "en": e.get("electronegativity_pauling"),
            "esem": e.get("electron_configuration_semantic"),
            "sum": summary_of(e),
        }
        for e in els
    ]

    cats = [[key, label] for key, label in CATEGORY_ORDER if key in normalised]
    # any category not in the ordered list (should not happen) appended at the end
    used = {c["cat"] for c in compact}
    extra = [k for k, _ in CATEGORY_ORDER if k in used]
    cats = [c for c in cats if c[0] in used]
    missing = sorted(used - {c[0] for c in cats})
    cats += [[k, k.title()] for k in missing]

    js = (
        "// Generated by scripts/build_elements_data.py — do not edit by hand.\n"
        "// Source: Bowserinator/Periodic-Table-JSON (PeriodicTableJSON.json).\n"
        "const ELEMENTS = "
        + json.dumps(compact, ensure_ascii=False, separators=(",", ":"))
        + ";\nconst ELEMENT_CATEGORIES = "
        + json.dumps(cats, ensure_ascii=False, separators=(",", ":"))
        + ";\nif (typeof window !== 'undefined') { window.ELEMENTS = ELEMENTS; window.ELEMENT_CATEGORIES = ELEMENT_CATEGORIES; }\n"
    )
    OUT.write_text(js, encoding="utf-8")
    print(f"wrote {OUT} ({OUT.stat().st_size / 1024:.1f} KB, {len(compact)} elements, {len(cats)} categories)")


if __name__ == "__main__":
    main()
