"""Curated learning content for the per-element rooms.

Learning design (Mayer's multimedia principles + retrieval practice):
each element room gets three short, learner-paced text stations --
    USES     where you actually meet this element (spatial contiguity:
             the card floats right next to its own explanation)
    XPER     one classic, real experiment or demonstration
    PNOTE    who found it / the human story (elaborative, narrative)
plus one honest 3D MODEL of how the atoms actually arrange themselves
(multimedia principle: words + picture beat words alone).

All content is intentionally ASCII and concise (coherence principle:
no extraneous decoration, no wall-of-text). Unknowns say so honestly.
"""

# symbol: (uses "a|b|c", classic experiment, person / history note)
CONTENT = {
    'H': ("rocket propellant|ammonia fertilisers|fuel cells",
          "Electrolysis of water splits H2O and releases H2 and O2 in a 2:1 volume ratio.",
          "Henry Cavendish (1766) called it 'inflammable air'; Lavoisier later named it hydrogen, 'water-former'."),
    'He': ("lifting balloons|MRI cryogenics|leak detection",
           "Fill a balloon with helium and it rises: He is about seven times lighter than air.",
           "Janssen and Lockyer spotted its spectral line in the 1868 solar corona; Ramsay isolated it on Earth in 1895."),
    'Li': ("EV batteries|heat-proof glass|mood-stabilising medicine",
           "Drop lithium into water: it fizzes gently and skims about, the calmest alkali-metal demo.",
           "Johan Arfwedson (1817) found it while analysing the mineral petalite."),
    'Be': ("X-ray windows|satellite mirrors|light alloys",
           "Beryllium foils pass X-rays easily, which is why X-ray tube windows are made of it.",
           "Vauquelin (1798) identified a new earth in beryl; Wohler and Bussy isolated the metal in 1828."),
    'B': ("heat-proof borosilicate glass|borax detergent|neutron shields",
          "Sprinkle boric acid on a flame and it flashes green, a classic qualitative test.",
          "Davy, Gay-Lussac and Thenard (1808) prepared impure boron by reducing boric acid with potassium."),
    'C': ("graphite pencils|diamond tools|all steel-making",
          "Burn an organic sample and bubble the gas through limewater: the white cloud proves the carbon.",
          "Known since antiquity as charcoal and soot; Lavoisier listed carbon as an element in 1789."),
    'N': ("ammonia fertilisers|food-freezing cryogenics|inert packaging",
          "Burn phosphorus in a closed flask standing over water: the leftover gas is nitrogen.",
          "Daniel Rutherford (1772) separated 'noxious air'; Chaptal later named it nitrogen."),
    'O': ("breathing oxygen|steel furnaces|welding torches",
          "Heat red mercuric oxide: bubbles of gas appear and a glowing splint relights, Priestley's 1774 demo.",
          "Priestley and Scheele discovered it independently in the 1770s; Lavoisier explained combustion with it."),
    'F': ("toothpaste fluoride|non-stick PTFE|uranium enrichment",
          "Hydrofluoric acid etches glass, a vivid demo of fluorine's unmatched reactivity.",
          "Moissan isolated F2 by electrolysis in 1886 and won the 1906 Nobel Prize for it."),
    'Ne': ("glowing signs|high-voltage indicators|cryogenic refrigerant",
           "Pass a discharge through neon gas: the tube glows its famous orange-red.",
           "Ramsay and Travers (1898) found it in liquefied air and named it 'the new one'."),
    'Na': ("table salt|sodium street lamps|reactor coolant",
           "A pea-sized piece of sodium on water fizzes, skims and ignites, the classic alkali demo.",
           "Humphry Davy (1807) isolated it by electrolysis of molten caustic soda."),
    'Mg': ("lightweight alloys|flares and fireworks|the chlorophyll centre",
           "Ignite an Mg ribbon for a blinding white flame, textbook photochemistry of flares.",
           "Recognised in magnesia by Black (1755); Davy isolated the metal in 1808."),
    'Al': ("drink cans|aircraft skins|power cables",
           "The thermite reaction: aluminium strips oxygen from iron oxide and pours molten iron.",
           "Oersted (1825) first produced it; the Hall-Heroult process (1886) made it cheap."),
    'Si': ("computer chips|solar panels|glass and quartz",
           "Dope a silicon wafer, shine light on the p-n junction and watch a meter deflect: a solar cell.",
           "Berzelius (1824) isolated it; Deville made it commercially usable in 1854."),
    'P': ("fertiliser phosphates|match heads|DNA and RNA backbone",
          "Strike a safety match: red phosphorus on the box ignites the head, friction chemistry live.",
          "Hennig Brand (1669) distilled it from urine, the first element with a known discoverer."),
    'S': ("sulfuric acid|rubber vulcanising|fungicides",
          "Burn sulfur in oxygen for its eerie blue flame and pungent SO2.",
          "Known since antiquity as brimstone; Lavoisier proved it an element in 1777."),
    'Cl': ("drinking-water treatment|PVC plastic|pool disinfectant",
           "Bubble chlorine through indigo dye solution and watch it decolourise: bleaching in action.",
           "Scheele (1774) made it from MnO2 and HCl; Davy proved it was an element in 1810."),
    'Ar': ("welding shields|light-bulb fill|double-glazing fill",
           "An argon-filled bulb keeps its filament from burning out: inert gas at work.",
           "Rayleigh and Ramsay (1894) found it hiding in air, the first noble gas."),
    'K': ("fertiliser potash|nerve signalling|soft soap",
          "Repeat the sodium demo with potassium for a lilac flame that identifies it.",
          "Davy (1807) isolated it from potash by electrolysis, days after sodium."),
    'Ca': ("cement and concrete|bones and teeth|plaster casts",
           "Calcium metal in water gives a steady stream of H2 and a cloudy Ca(OH)2 suspension.",
           "Davy (1808) electrolysed moist lime to isolate the metal."),
    'Sc': ("bike frames|stadium lamps|aerospace alloys",
           "Scandium iodide in lamps produces a sun-like white spectrum.",
           "Nilson (1879) isolated its oxide, slotting neatly into a gap Mendeleev had predicted."),
    'Ti': ("hip implants|jet engines|white paint (TiO2)",
           "Titanium screws integrate with living bone for decades, biocompatibility in action.",
           "Klaproth (1795) named it after the Titans; Hunter (1910) finally isolated the metal."),
    'V': ("tool steel|sulfuric-acid catalyst|flow batteries",
          "Vanadium pentoxide converts SO2 to SO3 in the contact process, colours dramatic: V2+ violet to V5+ yellow.",
          "Del Rio (1801) found it; Sefstrom (1830) rediscovered it and Wohler proved they matched."),
    'Cr': ("stainless steel|chrome plating|ruby-red pigments",
           "Trace chromium ions give ruby and emerald their colours, ligand-field chemistry.",
           "Vauquelin (1797) found it in Siberian crocoite ore."),
    'Mn': ("hardening steel|dry-cell batteries|the oxygen-releasing enzyme",
           "MnO2 catalyses hydrogen peroxide into a foam of oxygen, catalysis made visible.",
           "Johan Gahn (1774) isolated it from the ore pyrolusite."),
    'Fe': ("skyscraper steel|blood haemoglobin|magnets",
           "Leave a nail in water versus dry air: only the wet one rusts, corrosion control.",
           "The Iron Age metal, smelted since about 1200 BC."),
    'Co': ("battery cathodes|jet superalloys|deep-blue glass",
           "Look through cobalt glass at a flame: it filters sodium glare for cleaner flame tests.",
           "Georg Brandt (1735) proved it a new metal, exorcising the 'cobold' demons blamed for bad ore."),
    'Ni': ("stainless steel|rechargeable batteries|hydrogenation catalyst",
           "Raney nickel hydrogenates plant oils, the chemistry behind margarine.",
           "Axel Cronstedt (1751) isolated it from ore miners called kupfernickel, 'devil's copper'."),
    'Cu': ("electric wiring|water pipes|antimicrobial surfaces",
           "Dip iron wire in copper sulfate: a shining copper coat grows on it, displacement live.",
           "Smelted since about 5000 BC; the Romans mined it on Cyprus, hence 'cyprium', copper."),
    'Zn': ("rust galvanising|brass|sunscreen oxide",
           "Zinc bolted to steel corrodes first and protects it, sacrificial anodes on ships.",
           "Marggraf (1746) isolated the metal; its alloys were used millennia earlier."),
    'Ga': ("LED chips|fast 5G transistors|safe liquid thermometers",
           "A gallium spoon melts in hot tea (m.p. 29.8 C), the classic low-melting demo.",
           "Lecoq de Boisbaudran (1875) found it spectroscopically, exactly where Mendeleev predicted eka-aluminium."),
    'Ge': ("optical fibres|infrared lenses|the first transistors",
           "The point-contact transistor of 1947 was germanium, the demo that started electronics.",
           "Winkler (1886) confirmed Mendeleev's predicted eka-silicon, almost property for property."),
    'As': ("GaAs chips|bronze hardener|historic wood preservative",
           "The Marsh test turns arsenic into a mirror of metallic arsenic, the first forensic toxicology method.",
           "Albertus Magnus (c. 1250) is credited with isolating it."),
    'Se': ("photocopier drums|anti-dandruff shampoo|thin-film solar",
           "Shine light on selenium and its conductivity jumps, the photoeffect behind photocopiers.",
           "Berzelius (1817) discovered it in the sludge of his sulfuric-acid plant."),
    'Br': ("flame retardants|photographic film|water purifier",
           "Add bromine water to an alkene: the orange colour vanishes, the unsaturation test.",
           "Antoine Balard (1826) discovered it in the ash of seawater."),
    'Kr': ("powerful floodlights|airport runway lamps|double-glazing fill",
           "From 1960 to 1983 the metre was defined by 1,650,763.73 wavelengths of krypton-86 light.",
           "Ramsay and Travers (1898) found it in the last drops of liquefied air."),
    'Rb': ("atomic clocks|night-vision sensors|purple fireworks",
           "Rubidium vapour in a cell resonates at a razor-sharp frequency, the heart of tiny clocks.",
           "Bunsen and Kirchhoff (1861) discovered it by flame spectroscopy, a brand-new method finding brand-new elements."),
    'Sr': ("red fireworks|ferrite magnets|glow-in-the-dark paint",
           "Sprinkle strontium chloride on a flame for the crimson of every firework show.",
           "Adair Crawford (1790) distinguished it from barium; Davy isolated the metal in 1808."),
    'Y': ("white-LED phosphors|superconductor ceramics|solid-state lasers",
           "YAG:neodymium lasers cut and weld, yttrium aluminium garnet at work.",
           "Gadolin (1794) found a new earth in ytterbite; Wohler isolated the metal in 1828."),
    'Zr': ("reactor fuel cladding|ceramic knives|cubic zirconia gems",
           "Zircaloy lets neutrons through but keeps fission products in, why fuel rods wear it.",
           "Klaproth (1789) identified zirconia; Berzelius isolated the metal in 1824."),
    'Nb': ("MRI superconducting magnets|pipeline steel|body jewellery",
           "Nb-Ti wire chilled by liquid helium carries the enormous currents of MRI magnets.",
           "Charles Hatchett (1801) discovered it and named it columbium."),
    'Mo': ("tough high-temp steel|nitrogen-fixing enzymes|engine lubricants",
           "Molybdenum enzymes let legumes pull nitrogen from air, biochemistry's quiet hero.",
           "Scheele (1778) proved it distinct from lead; Hjelm (1781) isolated the metal."),
    'Tc': ("medical imaging (Tc-99m)|oil-well tracers|research",
           "Tc-99m lights up organs in tens of millions of SPECT scans every year.",
           "Perrier and Segre (1937) made it the first artificially produced element."),
    'Ru': ("chip interconnects|solar-cell dye|hardening platinum",
           "Ruthenium contacts in switches shrug off millions of on-off cycles.",
           "Karl Claus (1844) rediscovered it in platinum waste from Tartu and named it for Russia."),
    'Rh': ("exhaust catalytic converters|mirror coatings|thermocouples",
           "Rhodium surfaces turn toxic exhaust into N2, CO2 and water, the three-way catalyst.",
           "Wollaston (1803) isolated it from a rose-red salt, Greek 'rhodon', rose."),
    'Pd': ("exhaust catalysts|hydrogen filters|fuel-cell electrodes",
           "Palladium foil passes hydrogen and stops everything else, Sieverts' famous demo.",
           "Wollaston (1802-03) discovered it and first announced it anonymously, for a wager."),
    'Ag': ("contacts and jewellery|antibacterial coatings|solar paste",
           "Silver tarnishes black in sulfur fumes, then polishes bright, everyday redox chemistry.",
           "Known since antiquity as one of the seven metals of alchemy."),
    'Cd': ("thin-film solar panels|quantum-dot TVs|Ni-Cd batteries",
           "Cadmium selenide quantum dots glow in sizes tuned from blue to red, nanotech in a vial.",
           "Stromeyer and Hermann (1817) found it as an impurity in pharmacy zinc carbonate."),
    'In': ("touchscreens (ITO)|low-melting solder|LCDs",
           "Indium tin oxide makes your phone screen both transparent and conductive, hold it to the light.",
           "Reich and Richter (1863) spotted its bright indigo spectral line, hence the name."),
    'Sn': ("solder|tin-plated food cans|bronze",
           "Scratch a tin can's plating and rust wins, showing what the tin shield was doing.",
           "Alloyed into bronze since about 3000 BC; pure tin won the tin-vs-copper puzzle for early smiths."),
    'Sb': ("flame retardants|type metal|semiconductor dopant",
           "Antimony hardens lead: Gutenberg's type metal held crisp letters for centuries.",
           "Known in antiquity as stibnite eye makeup; its name is the root of both 'alchemy' and 'chemistry'."),
    'Te': ("thin-film solar (CdTe)|thermoelectric coolers|rubber curing",
           "Bismuth telluride chips cool CPU and power deep-space probes with the Seebeck effect.",
           "Reichenstein (1782) found it in Transylvanian gold ores; Klaproth named it in 1798."),
    'I': ("iodised salt|antiseptics|X-ray contrast agents",
          "Add iodine solution to starch and it snaps to blue-black, the classic starch test.",
          "Courtois (1811) found violet vapours while burning seaweed ash for saltpetre."),
    'Xe': ("ion thrusters|car headlamps|anaesthesia",
           "Xenon ion engines push spacecraft with a whisper of blue plasma for years.",
           "Ramsay and Travers (1898) discovered it in liquid-air residue; Greek xenos, 'stranger'."),
    'Cs': ("defines the SI second|drilling fluids|photocells",
           "A caesium fountain clock defines the second: exactly 9,192,631,770 oscillations.",
           "Bunsen and Kirchhoff (1860) discovered it with their spectroscope within minutes of seeing two blue lines."),
    'Ba': ("X-ray 'barium meal'|drilling mud|green fireworks",
           "Insoluble barium sulfate outlines the gut on X-rays, safe contrast imaging.",
           "Scheele (1774) identified baryta; Davy isolated the metal in 1808."),
    'La': ("hybrid-car batteries|camera lenses|oil-refining catalyst",
           "LaNi5 alloys soak up hydrogen like a sponge, storage for fuel-cell research.",
           "Mosander (1839) split ceria into pieces; his first 'lanthanum', the hidden one."),
    'Ce': ("exhaust catalysts|precision glass polishing|lighter flints",
           "Scrape a lighter flint (mischmetal, mostly Ce): sparks of cerium pyrophoricity.",
           "Berzelius, Klaproth and Hisinger (1803) independently identified it, naming it after the asteroid Ceres."),
    'Pr': ("magnet alloys|welding goggles|aircraft magnets",
           "Praseodymium glass tints welders' goggles to cut the intense yellow glare of molten metal.",
           "Von Welsbach (1885) split the old 'didymium' into praseodymium and neodymium."),
    'Nd': ("the strongest permanent magnets|wind-turbine generators|hard-drive magnets",
           "Hang a paperclip from a tiny NdFeB magnet: strength many times its weight, personal-audio tech.",
           "Von Welsbach (1885), twin discovery with praseodymium from didymium."),
    'Pm': ("nuclear batteries|luminous paint (historic)|thickness gauges",
           "Pm-147 betavoltaic batteries powered early pacemakers and luminous dials.",
           "Marinsky, Glendenin and Coryell (1945) found it in uranium fission products, the last rare earth to be identified."),
    'Sm': ("high-temperature magnets|cancer therapy research|reactor control",
           "Sm-Co magnets keep working red-hot where neodymium magnets would give up.",
           "Lecoq de Boisbaudran (1879) identified it spectroscopically in the mineral samarskite."),
    'Eu': ("euro-banknote security|red phosphors|anti-forgery inks",
           "Hold a euro note under UV: europium phosphors glow red, instant authenticity check.",
           "Demarcay (1901) separated it spectroscopically from samarium fractions."),
    'Gd': ("MRI contrast agents|neutron shielding|magneto-caloric cooling",
           "Gadolinium warms when magnetised and cools when released, magnetic refrigeration demos.",
           "Marignac (1880) detected it spectroscopically; Lecoq de Boisbaudran isolated a pure salt in 1886."),
    'Tb': ("green phosphors|sonar transducers|solid-state fuel cells",
           "Terfenol-D (Tb alloy) stretches in magnetic fields, the 'muscle' inside sonar.",
           "Mosander (1843) teased it out of yttria, one of many elements hiding there."),
    'Dy': ("EV motor magnets|nuclear control rods|lasers",
           "A dash of dysprosium keeps neodymium magnets magnetic when EV motors run hot.",
           "Lecoq de Boisbaudran (1886) separated it from holmium; Greek dysprositos, 'hard to get'."),
    'Ho': ("surgical lasers|magnetic-field concentration|glass colouring",
           "Holmium lasers cut tissue with minimal scarring in operating theatres.",
           "Soret and Delafontaine (1878) spotted it; Cleve isolated a pure sample in 1879."),
    'Er': ("fibre-optic amplifiers|laser surgery|pink glassware",
           "Er-doped fibre amplifiers boost light signals that carry the internet under oceans.",
           "Cleve (1879) separated it from erbia; Mosander had hinted at it decades earlier."),
    'Tm': ("portable X-ray sources|surgical lasers|europium phosphor activation",
           "Tm-170 served as a suitcase-sized X-ray source for field medicine.",
           "Cleve (1879) found it while splitting erbia, naming it for Thule, the far north."),
    'Yb': ("fibre lasers|record-breaking atomic clocks|stress gauges",
           "Ytterbium optical clocks are among the most accurate timepieces ever built.",
           "Marignac (1878) discovered a new earth in ytterbia; the metal itself came much later."),
    'Lu': ("PET scanner crystals|refinery catalyst|dating ancient rocks",
           "LSO scintillators doped with cerium flash when hit by PET gamma rays.",
           "Urbain (1907) separated lutecium from ytterbia after decades of rare-earth disputes."),
    'Hf': ("reactor control rods|jet-engine superalloys|plasma torches",
           "Hafnium drinks neutrons, the perfect partner to zirconium cladding in reactors.",
           "Coster and Hevesy (1923) found it in Copenhagen by X-ray spectroscopy, predicted by Bohr's theory."),
    'Ta': ("smartphone capacitors|surgical implants|chemical plant lining",
           "Tantalum capacitors pack enormous charge into millimetres of every phone.",
           "Ekeberg (1802) named it for Tantalus, condemned to frustration, since it resisted acid attack."),
    'W': ("light-bulb filaments|drill-bit tips|X-ray shielding",
           "Run a tungsten filament white-hot at 3000 C and it simply refuses to melt.",
           "The Elhuyar brothers (1783) extracted it from wolframite, beating the mineral's stubborn name."),
    'Re': ("jet-engine blades|thermocouples|hydrogenation catalyst",
           "Rhenium lets turbine blades glow red-hot inside modern jet engines.",
           "Noddack, Tacke and Berg (1925) detected it by X-ray spectroscopy and named it for the Rhine."),
    'Os': ("fountain-pen nibs|instrument pivots|fingerprint detection",
           "Osmium is the densest natural element, about 22.6 g/cm3, twice lead's heft.",
           "Tennant (1803) found it in platinum residue; its oxide's harsh smell gave it the name."),
    'Ir': ("spark plugs|crucibles|the 1889 mass standards",
           "Iridium-rich clay marks the asteroid impact that ended the dinosaurs.",
           "Tennant and friends (1803) discovered it with osmium in the same black platinum residue."),
    'Pt': ("exhaust catalysts|wedding rings|the anti-cancer drug cisplatin",
           "Heat a Pt wire glowing and hold it over ammonia vapour: it catalyses the reaction unaided.",
           "Ulloa (1735) described Colombian 'platina', little silver; Wollaston industrialised it."),
    'Au': ("microchip contacts|bullion|gold-leaf gilding",
           "Beat gold into leaf thinner than light waves: it lets sunshine through, greenish.",
           "Known since antiquity; the incorruptible metal of kings and coinage."),
    'Hg': ("fluorescent lamps|historic thermometers|gold amalgamation",
           "A droplet of mercury conducts and flows evenly, the classic thermometer liquid.",
           "Known to ancients as quicksilver, the only metal liquid at room temperature."),
    'Tl': ("infrared optics|gamma detectors|banned rat poison",
           "Thallium salts turn a flame intense green, the spectroscopic fingerprint.",
           "Crookes (1861) discovered it by the bright green line in his spectroscope."),
    'Pb': ("car batteries|radiation shields|roof flashings",
           "Plates of lead in sulfuric acid charge and discharge for years, the starter battery.",
           "Known since antiquity; Roman water pipes gave plumbing its name (plumbum)."),
    'Bi': ("stomach medicine|fire-sprinkler alloys|cosmetic shimmer",
           "Bi-55% alloys melt in hot water, the plugs inside fire sprinklers.",
           "Geoffroy (1753) proved it a distinct metal, separate from lead."),
    'Po': ("antistatic brushes|historic space heaters|research",
           "Polonium-210 ions neutralise static on photographic film and cloth.",
           "Marie and Pierre Curie (1898) discovered it and named it for Marie's homeland, Poland."),
    'At': ("targeted alpha-therapy research|environmental tracers|research",
           "Astatine-211 is tested to ferry alpha radiation directly into tumour cells.",
           "Segre and colleagues (1940) synthesised it in a cyclotron at Berkeley."),
    'Rn': ("radon home monitoring|geological tracers|historic spa therapy",
           "Radon detectors in basements measure the gas that seeps from rock and soil.",
           "Dorn (1900) noticed a heavy radioactive gas escaping from radium, 'radium emanation'."),
    'Fr': ("fundamental symmetry tests|atom traps|research",
           "Catching a few thousand francium atoms lets physicists test the standard model.",
           "Marguerite Perey (1939) discovered it in actinium decay chains, the last naturally occurring element."),
    'Ra': ("early cancer therapy|luminous dials (historic)|research",
           "Radium paint glowed on watch dials; the radium girls' story founded workplace safety law.",
           "The Curies (1898) discovered it; Curie and Debierne isolated the metal in 1910."),
    'Ac': ("neutron sources|radiotherapy research|environmental tracers",
           "Actinium-227 sources glowed blue in the dark from ionised air.",
           "Debierne (1899) found it in pitchblende residue; Giesel (1902) discovered it independently."),
    'Th': ("thorium reactor research|gas mantles|specialty alloys",
           "A thorium dioxide gas mantle glows brilliant white over a flame, incandescence in every old lamp.",
           "Berzelius (1829) discovered it in a Norwegian mineral and named it after Thor."),
    'Pa': ("dating ocean sediments|fundamental research|research",
           "Pa-231/Th-230 ratios in seabed cores date millions of years of climate history.",
           "Fajans and Gohring (1913) saw it first; Hahn and Meitner named it protactinium."),
    'U': ("reactor fuel|radiometric dating|ship ballast",
           "Bring enough U-235 together and the chain reaction runs itself, reactor physics 101.",
           "Klaproth (1789) extracted it from pitchblende, naming it after the newly found planet Uranus."),
    'Np': ("neutron detectors|research|research",
           "Neptunium-237 shows up in every spent fuel rod, the first step of transmutation.",
           "McMillan (1940) identified it, the first transuranium element, named for the next planet out."),
    'Pu': ("deep-space RTG power|reactor fuel|historic weapons",
           "Voyager and Curiosity still run on Pu-238 heat converted to electricity.",
           "Seaborg's Berkeley team (1940-41) synthesised and chemically identified it."),
    'Am': ("smoke detectors|thickness gauges|research",
           "Americium-241 in a smoke detector ionises air; smoke interrupts the tiny current, alarm.",
           "Seaborg's Chicago team (1944) created it during the Manhattan Project and named it for the Americas."),
    'Cm': ("Apollo lunar instruments|spacecraft power|research",
           "Curium heaters kept Apollo lunar surface instruments warm through the night.",
           "Seaborg's team (1944) named it for Marie and Pierre Curie, following their actinide path."),
    'Bk': ("target material for making heavier elements|research|research",
           "Berkelium targets were irradiated to create the first atoms of tennessine.",
           "Thompson, Ghiorso and Seaborg (1949) made it in Berkeley's 60-inch cyclotron."),
    'Cf': ("neutron sources|reactor start-up|oil-well logging",
           "Cf-252 neutrons kick-start reactors and probe for oil in boreholes.",
           "Thompson, Street, Ghiorso and Seaborg (1950) made it by alpha bombardment of curium."),
    'Es': ("research targets for heavier elements|research|research",
           "Einsteinium-253 targets enabled the first mendelevium atoms.",
           "Ghiorso and colleagues (1952) found it in the debris of the first hydrogen-bomb test."),
    'Fm': ("research|research|research",
           "Fermium-257 marks the heaviest element creatable by pure neutron capture.",
           "Ghiorso and colleagues (1952-53) identified it in hydrogen-bomb debris."),
    'Md': ("atom-at-a-time chemistry|research|research",
           "Chemists measured mendelevium's chemistry with literally individual atoms.",
           "Ghiorso and colleagues (1955) produced 17 atoms and named it for Mendeleev."),
    'No': ("research|research|research",
           "Nobelium chemistry had to be unravelled atom by atom in special solutions.",
           "Disputed results in 1957 resolved by Dubna and Berkeley work (1958-66); named for Alfred Nobel."),
    'Lr': ("research|research|research",
           "Lawrencium closed the actinide row, the 103rd element on the periodic table.",
           "Ghiorso, Sikkeland, Larsh and Latimer (1961) named it for cyclotron inventor Ernest Lawrence."),
    'Rf': ("research|research|research",
           "Rutherfordium behaves chemically like hafnium, confirming its place on the table.",
           "Berkeley and Dubna fought over element 104 for decades; IUPAC settled on Rutherford (1964/1969)."),
    'Db': ("research|research|research",
           "Dubnium chemistry resembles niobium and tantalum, probed with single atoms.",
           "Dubna and Berkeley both claimed element 105; the name honours the town of Dubna."),
    'Sg': ("research|research|research",
           "Six atoms of seaborgium hexacarbonyl were volatile enough to study as a gas.",
           "Berkeley (1974) made it; Seaborg became the first person named after an element while alive."),
    'Bh': ("research|research|research",
           "Only a handful of bohrium atoms have ever existed, each for seconds.",
           "Munzenberg and Armbruster at GSI Darmstadt (1981), named for Niels Bohr."),
    'Hs': ("research|research|research",
           "Hassium tetroxide gas confirmed it behaves like a heavier osmium.",
           "GSI Darmstadt (1984), named for the Latin form of Hesse."),
    'Mt': ("research|research|research",
           "Meitnerium atoms are made one fusion event at a time, then gone in seconds.",
           "GSI Darmstadt (1982), named for Lise Meitner, co-discoverer of nuclear fission."),
    'Ds': ("research|research|research",
           "Darmstadtium forms from lead and nickel ions colliding at 30,000 km/s.",
           "GSI Darmstadt (1994), named for the city of Darmstadt."),
    'Rg': ("research|research|research",
           "Roentgenium seems to behave like a super-heavy gold, relativistic effects included.",
           "GSI Darmstadt (1994), named for Rontgen, discoverer of X-rays."),
    'Cn': ("research|research|research",
           "Copernicium may be a volatile liquid metal, mercury's relativistic cousin.",
           "GSI Darmstadt (1996), named for Copernicus in 2010."),
    'Nh': ("research|research|research",
           "Nihonium was the first element ever discovered in Asia.",
           "RIKEN, Japan (2004-05), Kosuke Morita's team; nihon means Japan."),
    'Fl': ("research|research|research",
           "Flerovium atoms hint at an island of stability ahead on the chart.",
           "Dubna-LLNL (1999), named for the Flerov Laboratory of Nuclear Reactions."),
    'Mc': ("research|research|research",
           "Moscovium forms when calcium-48 ions smash into americium targets.",
           "Dubna-LLNL (2003), named for the Moscow region."),
    'Lv': ("research|research|research",
           "Livermorium decays within tens of milliseconds of being born.",
           "Dubna-LLNL (2000), named for Lawrence Livermore National Laboratory."),
    'Ts': ("research|research|research",
           "Tennessine atoms survived only milliseconds, long enough to count their decays.",
           "Dubna-ORNL (2010), the second element named for a US state, after Tennessee's Oak Ridge lab."),
    'Og': ("research|research|research",
           "Oganesson may even be a solid or semiconductor at room temperature, a very strange noble gas.",
           "Dubna-LLNL (2002), named for Yuri Oganessian, still the heaviest atom known."),
}

# How the atoms actually arrange themselves, and an honest caption for it.
# Types understood by buildLattice() in assets/lib/primitives.js:
#   atom | dumbbell | tetra | ring8 | sc | bcc | fcc | hcp | diamond
MODEL = {
    'H': ('dumbbell', 'H2: hydrogen travels as paired atoms'),
    'He': ('atom', 'a monatomic noble gas: one lone sphere'),
    'Li': ('bcc', 'body-centred cubic metal'),
    'Be': ('hcp', 'hexagonal close-packed metal'),
    'B': ('atom', 'complex icosahedral B12 networks (schematic)'),
    'C': ('diamond', 'diamond-type covalent network; graphite instead forms layers'),
    'N': ('dumbbell', 'N2: 78% of every breath, in pairs'),
    'O': ('dumbbell', 'O2: paired atoms (ozone, O3, is the rarer cousin)'),
    'F': ('dumbbell', 'F2: the most reactive molecule, in pairs'),
    'Ne': ('atom', 'a monatomic noble gas'),
    'Na': ('bcc', 'body-centred cubic metal'),
    'Mg': ('hcp', 'hexagonal close-packed metal'),
    'Al': ('fcc', 'face-centred cubic metal'),
    'Si': ('diamond', 'diamond-type network: the chip-maker lattice'),
    'P': ('tetra', 'P4 tetrahedra (white phosphorus; red and black P form networks)'),
    'S': ('ring8', 'crown-shaped S8 rings'),
    'Cl': ('dumbbell', 'Cl2: a greenish gas of paired atoms'),
    'Ar': ('atom', 'a monatomic noble gas'),
    'K': ('bcc', 'body-centred cubic metal'),
    'Ca': ('fcc', 'face-centred cubic metal'),
    'Sc': ('hcp', 'hexagonal close-packed metal'),
    'Ti': ('hcp', 'hexagonal close-packed metal'),
    'V': ('bcc', 'body-centred cubic metal'),
    'Cr': ('bcc', 'body-centred cubic metal'),
    'Mn': ('atom', 'complex alpha-Mn arrangement (schematic)'),
    'Fe': ('bcc', 'body-centred cubic at room temperature'),
    'Co': ('hcp', 'hexagonal close-packed metal'),
    'Ni': ('fcc', 'face-centred cubic metal'),
    'Cu': ('fcc', 'face-centred cubic metal'),
    'Zn': ('hcp', 'hexagonal close-packed metal'),
    'Ga': ('atom', 'paired atoms in orthorhombic layers (schematic)'),
    'Ge': ('diamond', 'diamond-type covalent network'),
    'As': ('atom', 'layered rhombohedral sheets (schematic)'),
    'Se': ('atom', 'helical chain molecules (schematic)'),
    'Br': ('dumbbell', 'Br2: a fuming liquid of paired atoms'),
    'Kr': ('atom', 'a monatomic noble gas'),
    'Rb': ('bcc', 'body-centred cubic metal'),
    'Sr': ('fcc', 'face-centred cubic metal'),
    'Y': ('hcp', 'hexagonal close-packed metal'),
    'Zr': ('hcp', 'hexagonal close-packed metal (hot beta-Zr is bcc)'),
    'Nb': ('bcc', 'body-centred cubic metal'),
    'Mo': ('bcc', 'body-centred cubic metal'),
    'Tc': ('hcp', 'hexagonal close-packed metal'),
    'Ru': ('hcp', 'hexagonal close-packed metal'),
    'Rh': ('fcc', 'face-centred cubic metal'),
    'Pd': ('fcc', 'face-centred cubic metal'),
    'Ag': ('fcc', 'face-centred cubic metal'),
    'Cd': ('hcp', 'hexagonal close-packed metal'),
    'In': ('atom', 'distorted face-centred tetragonal (schematic)'),
    'Sn': ('atom', 'beta-tin tetragonal (schematic; deep cold powders it)'),
    'Sb': ('atom', 'layered rhombohedral sheets (schematic)'),
    'Te': ('atom', 'helical chain molecules (schematic)'),
    'I': ('dumbbell', 'I2: violet crystals of paired atoms'),
    'Xe': ('atom', 'a monatomic noble gas'),
    'Cs': ('bcc', 'body-centred cubic metal'),
    'Ba': ('bcc', 'body-centred cubic metal'),
    'La': ('hcp', 'double-hexagonal close-packed metal (schematic)'),
    'Ce': ('fcc', 'face-centred cubic metal'),
    'Pr': ('hcp', 'hexagonal close-packed metal'),
    'Nd': ('hcp', 'hexagonal close-packed metal'),
    'Pm': ('hcp', 'hexagonal close-packed metal'),
    'Sm': ('atom', 'rhombohedral layered metal (schematic)'),
    'Eu': ('bcc', 'body-centred cubic metal'),
    'Gd': ('hcp', 'hexagonal close-packed metal'),
    'Tb': ('hcp', 'hexagonal close-packed metal'),
    'Dy': ('hcp', 'hexagonal close-packed metal'),
    'Ho': ('hcp', 'hexagonal close-packed metal'),
    'Er': ('hcp', 'hexagonal close-packed metal'),
    'Tm': ('hcp', 'hexagonal close-packed metal'),
    'Yb': ('fcc', 'face-centred cubic metal'),
    'Lu': ('hcp', 'hexagonal close-packed metal'),
    'Hf': ('hcp', 'hexagonal close-packed metal (the hot form is bcc)'),
    'Ta': ('bcc', 'body-centred cubic metal'),
    'W': ('bcc', 'body-centred cubic metal'),
    'Re': ('hcp', 'hexagonal close-packed metal'),
    'Os': ('hcp', 'hexagonal close-packed metal'),
    'Ir': ('fcc', 'face-centred cubic metal'),
    'Pt': ('fcc', 'face-centred cubic metal'),
    'Au': ('fcc', 'face-centred cubic metal'),
    'Hg': ('atom', 'liquid at room temperature: no lattice to show'),
    'Tl': ('hcp', 'hexagonal close-packed metal'),
    'Pb': ('fcc', 'face-centred cubic metal'),
    'Bi': ('atom', 'layered rhombohedral sheets (schematic)'),
    'Po': ('sc', 'simple cubic: the rarest packing in the table'),
    'At': ('atom', 'structure unknown: only trace amounts exist'),
    'Rn': ('atom', 'a monatomic noble gas'),
    'Fr': ('atom', 'structure inferred: bcc, but never seen in bulk'),
    'Ra': ('bcc', 'body-centred cubic metal'),
    'Ac': ('fcc', 'face-centred cubic metal'),
    'Th': ('fcc', 'face-centred cubic metal'),
    'Pa': ('atom', 'body-centred tetragonal (schematic)'),
    'U': ('atom', 'orthorhombic metallic layers (schematic)'),
    'Np': ('atom', 'complex orthorhombic metal (schematic)'),
    'Pu': ('atom', 'monoclinic: it has seven solid forms!'),
    'Am': ('hcp', 'hexagonal close-packed metal'),
    'Cm': ('hcp', 'hexagonal close-packed metal'),
    'Bk': ('hcp', 'hexagonal close-packed metal'),
    'Cf': ('atom', 'structure inferred: hcp, known only in micrograms'),
    'Es': ('atom', 'structure unknown: made a few atoms at a time'),
    'Fm': ('atom', 'structure unknown'),
    'Md': ('atom', 'structure unknown'),
    'No': ('atom', 'structure unknown'),
    'Lr': ('atom', 'structure unknown'),
    'Rf': ('atom', 'structure unknown: only atoms ever made'),
    'Db': ('atom', 'structure unknown'),
    'Sg': ('atom', 'structure unknown'),
    'Bh': ('atom', 'structure unknown'),
    'Hs': ('atom', 'structure unknown'),
    'Mt': ('atom', 'structure unknown'),
    'Ds': ('atom', 'structure unknown'),
    'Rg': ('atom', 'structure unknown'),
    'Cn': ('atom', 'structure unknown: may be a volatile liquid'),
    'Nh': ('atom', 'structure unknown'),
    'Fl': ('atom', 'structure unknown'),
    'Mc': ('atom', 'structure unknown'),
    'Lv': ('atom', 'structure unknown'),
    'Ts': ('atom', 'structure unknown'),
    'Og': ('atom', 'structure unknown: may be solid at room temperature'),
}


def get_content(symbol: str) -> dict:
    """Merged learning content for one element symbol."""
    c = CONTENT.get(symbol)
    m = MODEL.get(symbol, ("atom", "structure unknown"))
    if not c:
        return {
            "u": ["pure research"],
            "xp": "Observed only atom-by-atom in heavy-ion accelerators.",
            "pn": "Synthesised in a particle laboratory; bulk samples will likely never exist.",
            "mo": {"t": m[0], "c": m[1]},
        }
    return {
        "u": c[0].split("|"),
        "xp": c[1],
        "pn": c[2],
        "mo": {"t": m[0], "c": m[1]},
    }
